apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: garage
  namespace: storage
  labels:
    app: garage
spec:
  serviceName: garage
  replicas: 1
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      containers:
        - name: garage
          image: dxflrs/garage:v1.0.1
          imagePullPolicy: IfNotPresent
          command: ["/garage", "server"]
          env:
            - name: GARAGE_ALLOW_WORLD_READABLE_SECRETS
              value: "true"
          ports:
            - name: s3-api
              containerPort: 3900
            - name: rpc
              containerPort: 3901
            - name: admin-api
              containerPort: 3903
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /etc/garage.toml
              subPath: garage.toml
              readOnly: true
            - name: secrets
              mountPath: /etc/garage/secrets
              readOnly: true
            - name: meta
              mountPath: /var/lib/garage/meta
            - name: data
              mountPath: /var/lib/garage/data
      volumes:
        - name: config
          configMap:
            name: garage-config
        - name: secrets
          secret:
            secretName: garage-secret
            defaultMode: 0400
  volumeClaimTemplates:
    - metadata:
        name: meta
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
