apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-registry
  namespace: container-registry
  labels:
    app: local-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-registry
  template:
    metadata:
      labels:
        app: local-registry
    spec:
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              hostPort: 5000
              name: registry
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: registry-storage
          hostPath:
            path: /var/lib/container-registry
            type: DirectoryOrCreate
