apiVersion: v1
kind: Namespace
metadata:
  name: container-registry
---
apiVersion: v1
kind: Service
metadata:
  name: local-registry
  namespace: container-registry
  labels:
    app: local-registry
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
      name: registry
  selector:
    app: local-registry
